### ISSUE TITLE
Trouble w/ installer.py

### ISSUE THREAD

**Issue by Fackles** [Magnus167/jarPhys#5]
After trying to run installation onto my External USB, there seemed to be some trouble with completing the installation.

The additional folders did not appear, must be due to the `ModuleNotFoundError: No module named 'requests'` I get in Powershell.

Hopefully this is an easy fix UwU
Thanks :)

PS - I love the name _JarPhys_ hehe :3

**Comment by Magnus167** [comment]
Updated installer.py to account for that. 
Let me know if the issue is closed;

Technical update:
Updated requirements.txt to include 'requests' so pip installs it right before the google drive module


Also - thank you :) Feedback highly appreciated <3
